language: node_js
node_js:
  - 10.19.0
cache: npm
install:
  - npm install
script:
  - npm run test
  - npm run build
env:
  global:
    secure: nxl/IvuqbppvO4U6jnitZVInivSVkYJJ2zTY8z+7ngelKZ/6+/pIdk0iW/gbykvGlvG7+u8UNzaBjfWm6SiRmR8tHG7Q987aSWof1AAfa71dJqOcmIsTQR2hJSu2InoJVIHxRbtJGi3WjR7VzJkpaDKQa4g13TIf2xbWrxni0aE1T9IBEftWnnqvhi9UWVq0eKwzDd0LemLOharj/0CajpZcqmEdv23uMFS4pClPICExnhG3BggNT0tQNjt7X3QFJKhApB+rsKTavGH7HauKGgg73saiiXRlpwum8wRcFsPxBf6BmV26Efw6aIWnzpsQFf2SVcqyGnMtPqfJ3YOHszPvm53FYAArBTTCVxNcll3UUGQzHJ1MeQYLzvLWRJQ3CDz1w1jVjeJvvsp048L6ih91+mRJ6H13ZQXuf8eF97wGBhxJ9Nz3bqNARX5Heg96+HQucgj1xMOioJslW9Sfo9R9ucyDgqmim+8dz4Jyg/6dpzNVNZk5tgStJaarj9PGZ9/KEDE2MDy+RkeEZgZrNLxMWeCskjFitxl/S4zxlxYocPeXKs702NOB9KL8a6RQPEbSbYhZ0AKP18z/ZVWRJaxFjZYihUZCtesTg/XeY85GMzXpBGNTj/xAefUCOStBi63YdTaA+uV0hPzqVWsKqUsfVpdUbtjtOnPHwhE2wGU=
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: nxl/IvuqbppvO4U6jnitZVInivSVkYJJ2zTY8z+7ngelKZ/6+/pIdk0iW/gbykvGlvG7+u8UNzaBjfWm6SiRmR8tHG7Q987aSWof1AAfa71dJqOcmIsTQR2hJSu2InoJVIHxRbtJGi3WjR7VzJkpaDKQa4g13TIf2xbWrxni0aE1T9IBEftWnnqvhi9UWVq0eKwzDd0LemLOharj/0CajpZcqmEdv23uMFS4pClPICExnhG3BggNT0tQNjt7X3QFJKhApB+rsKTavGH7HauKGgg73saiiXRlpwum8wRcFsPxBf6BmV26Efw6aIWnzpsQFf2SVcqyGnMtPqfJ3YOHszPvm53FYAArBTTCVxNcll3UUGQzHJ1MeQYLzvLWRJQ3CDz1w1jVjeJvvsp048L6ih91+mRJ6H13ZQXuf8eF97wGBhxJ9Nz3bqNARX5Heg96+HQucgj1xMOioJslW9Sfo9R9ucyDgqmim+8dz4Jyg/6dpzNVNZk5tgStJaarj9PGZ9/KEDE2MDy+RkeEZgZrNLxMWeCskjFitxl/S4zxlxYocPeXKs702NOB9KL8a6RQPEbSbYhZ0AKP18z/ZVWRJaxFjZYihUZCtesTg/XeY85GMzXpBGNTj/xAefUCOStBi63YdTaA+uV0hPzqVWsKqUsfVpdUbtjtOnPHwhE2wGU=
  branch: master
