export const TAKE_ONE_FROM_STOCK: string = "TAKE_ONE_FROM_STOCK";
export const REVERSE_STOCK: string = "REVERSE_STOCK";
export const ADD_CARD_TO_FOUNDATION: string = "ADD_CARD_TO_FOUNDATION";
export const REMOVE_CARD_MOVED_TO_FOUNDATION: string =
  "REMOVE_CARD_MOVED_TO_FOUNDATION";
