export const TAKE_ONE_FROM_STOCK: string = "TAKE_ONE_FROM_STOCK";
export const REVERSE_STOCK: string = "REVERSE_STOCK";
export const ADD_CARD_TO_FIRST_FOUNDATION: string =
  "ADD_CARD_TO_FIRST_FOUNDATION";
export const ADD_CARD_TO_SECOND_FOUNDATION: string =
  "ADD_CARD_TO_SECOND_FOUNDATION";
export const ADD_CARD_TO_THIRD_FOUNDATION: string =
  "ADD_CARD_TO_THIRD_FOUNDATION";
export const ADD_CARD_TO_FOURTH_FOUNDATION: string =
  "ADD_CARD_TO_FOURTH_FOUNDATION";
export const REMOVE_CARD_MOVED_TO_FOUNDATION: string =
  "REMOVE_CARD_MOVED_TO_FOUNDATION";
export const ADD_CARD_TO_PILE: string = "ADD_CARD_TO_PILE";
export const REMOVE_CARD_FROM_PILE: string = "REMOVE_CARD_FROM_PILE";
