export const cardTypes: string[] = [
  "aceOfHearts",
  "twoOfHearts",
  "threeOfHearts",
  "fourOfHearts",
  "fiveOfHearts",
  "sixOfHearts",
  "sevenOfHearts",
  "eigthOfHearts",
  "nineOfHearts",
  "tenOfHearts",
  "jackOfHearts",
  "queenOfHearts",
  "kingOfHearts",
  "aceOfSpades",
  "twoOfSpades",
  "threeOfSpades",
  "fourOfSpades",
  "fiveOfSpades",
  "sixOfSpades",
  "sevenOfSpades",
  "eigthOfSpades",
  "nineOfSpades",
  "tenOfSpades",
  "jackOfSpades",
  "queenOfSpades",
  "kingOfSpades",
  "aceOfDiamonds",
  "twoOfDiamonds",
  "threeOfDiamonds",
  "fourOfDiamonds",
  "fiveOfDiamonds",
  "sixOfDiamonds",
  "sevenOfDiamonds",
  "eigthOfDiamonds",
  "nineOfDiamonds",
  "tenOfDiamonds",
  "jackOfDiamonds",
  "queenOfDiamonds",
  "kingOfDiamonds",
  "aceOfClubs",
  "twoOfClubs",
  "threeOfClubs",
  "fourOfClubs",
  "fiveOfClubs",
  "sixOfClubs",
  "sevenOfClubs",
  "eigthOfClubs",
  "nineOfClubs",
  "tenOfClubs",
  "jackOfClubs",
  "queenOfClubs",
  "kingOfClubs",
];

const cardRank: string[] = [
  "ace",
  "two",
  "three",
  "four",
  "five",
  "six",
  "seven",
  "eight",
  "nine",
  "ten",
  "jack",
  "queen",
  "king",
];

const cardConfigs: (string | undefined)[][] = [
  ["diamonds", undefined, "black"],
  ["spades", undefined, "black"],
  ["hearts", undefined, "red"],
  ["clubs", undefined, "red"],
];

export const createCards: (string | undefined)[][] = cardRank
  .map((rank) => cardConfigs.map((config) => [rank, ...config]))
  .reduce((a, b) => a.concat(b), []);
