export const cardTypes: string[] = [
  "aceOfHearts",
  "eigthOfHearts",
  "fiveOfHearts",
  "fourOfHearts",
  "jackOfHearts",
  "kingOfHearts",
  "nineOfHearts",
  "queenOfHearts",
  "sevenOfHearts",
  "sixOfHearts",
  "tenOfHearts",
  "twoOfHearts",
  "threeOfHearts",
];
