interface foundationConfig {
  [key: string]: string[];
}

export const foundationConfig: foundationConfig = {
  Hearts: [
    "aceOfHearts",
    "twoOfHearts",
    "threeOfHearts",
    "fourOfHearts",
    "fiveOfHearts",
    "sixOfHearts",
    "sevenOfHearts",
    "eigthOfHearts",
    "nineOfHearts",
    "tenOfHearts",
    "jackOfHearts",
    "queenOfHearts",
    "kingOfHearts",
  ],
  Spades: [
    "aceOfSpades",
    "twoOfSpades",
    "threeOfSpades",
    "fourOfSpades",
    "fiveOfSpades",
    "sixOfSpades",
    "sevenOfSpades",
    "eigthOfSpades",
    "nineOfSpades",
    "tenOfSpades",
    "jackOfSpades",
    "queenOfSpades",
    "kingOfSpades",
  ],
  Diamonds: [
    "aceOfDiamonds",
    "twoOfDiamonds",
    "threeOfDiamonds",
    "fourOfDiamonds",
    "fiveOfDiamonds",
    "sixOfDiamonds",
    "sevenOfDiamonds",
    "eigthOfDiamonds",
    "nineOfDiamonds",
    "tenOfDiamonds",
    "jackOfDiamonds",
    "queenOfDiamonds",
    "kingOfDiamonds",
  ],
  Clubs: [
    "aceOfClubs",
    "twoOfClubs",
    "threeOfClubs",
    "fourOfClubs",
    "fiveOfClubs",
    "sixOfClubs",
    "sevenOfClubs",
    "eigthOfClubs",
    "nineOfClubs",
    "tenOfClubs",
    "jackOfClubs",
    "queenOfClubs",
    "kingOfClubs",
  ],
};
