export const foundationHeartsConfig: string[] = [
  "aceOfHearts",
  "twoOfHearts",
  "threeOfHearts",
  "fourOfHearts",
  "fiveOfHearts",
  "sixOfHearts",
  "sevenOfHearts",
  "eigthOfHearts",
  "nineOfHearts",
  "tenOfHearts",
  "jackOfHearts",
  "queenOfHearts",
  "kingOfHearts",
];

export const foundationClubsConfig: string[] = [
  "aceOfClubs",
  "twoOfClubs",
  "threeOfClubs",
  "fourOfClubs",
  "fiveOfClubs",
  "sixOfClubs",
  "sevenOfClubs",
  "eigthOfClubs",
  "nineOfClubs",
  "tenOfClubs",
  "jackOfClubs",
  "queenOfClubs",
  "kingOfClubs",
];

export const foundationDiamondsConfig: string[] = [
  "aceOfDiamonds",
  "twoOfDiamonds",
  "threeOfDiamonds",
  "fourOfDiamonds",
  "fiveOfDiamonds",
  "sixOfDiamonds",
  "sevenOfDiamonds",
  "eigthOfDiamonds",
  "nineOfDiamonds",
  "tenOfDiamonds",
  "jackOfDiamonds",
  "queenOfDiamonds",
  "kingOfDiamonds",
];

export const foundationSpadesConfig: string[] = [
  "aceOfSpades",
  "twoOfSpades",
  "threeOfSpades",
  "fourOfSpades",
  "fiveOfSpades",
  "sixOfSpades",
  "sevenOfSpades",
  "eigthOfSpades",
  "nineOfSpades",
  "tenOfSpades",
  "jackOfSpades",
  "queenOfSpades",
  "kingOfSpades",
];

interface foundationConfig {
  [key: string]: string[];
}

export const foundationConfig: foundationConfig = {
  hearts: [
    "aceOfHearts",
    "twoOfHearts",
    "threeOfHearts",
    "fourOfHearts",
    "fiveOfHearts",
    "sixOfHearts",
    "sevenOfHearts",
    "eigthOfHearts",
    "nineOfHearts",
    "tenOfHearts",
    "jackOfHearts",
    "queenOfHearts",
    "kingOfHearts",
  ],
  spades: [
    "aceOfSpades",
    "twoOfSpades",
    "threeOfSpades",
    "fourOfSpades",
    "fiveOfSpades",
    "sixOfSpades",
    "sevenOfSpades",
    "eigthOfSpades",
    "nineOfSpades",
    "tenOfSpades",
    "jackOfSpades",
    "queenOfSpades",
    "kingOfSpades",
  ],
  diamonds: [
    "aceOfDiamonds",
    "twoOfDiamonds",
    "threeOfDiamonds",
    "fourOfDiamonds",
    "fiveOfDiamonds",
    "sixOfDiamonds",
    "sevenOfDiamonds",
    "eigthOfDiamonds",
    "nineOfDiamonds",
    "tenOfDiamonds",
    "jackOfDiamonds",
    "queenOfDiamonds",
    "kingOfDiamonds",
  ],
  clubs: [
    "aceOfClubs",
    "twoOfClubs",
    "threeOfClubs",
    "fourOfClubs",
    "fiveOfClubs",
    "sixOfClubs",
    "sevenOfClubs",
    "eigthOfClubs",
    "nineOfClubs",
    "tenOfClubs",
    "jackOfClubs",
    "queenOfClubs",
    "kingOfClubs",
  ],
};
