name: Deploy Solitaire
on:
  push:
    branches:
      - github_actions
jobs:
  run_all_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.0"
      - run: yarn global add lerna
      - run: yarn install
      - run: yarn test:ci
      - run: yarn build:packages
      - run: yarn cy:ci
      - uses: codecov/codecov-action@v2
