name: Deploy Solitaire
on:
  push:
    branches:
      - github_actions
jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/run-tests
      - uses: codecov/codecov-action@v2
