name: Deploy Solitaire
on:
  push:
    branches:
      - master
jobs:
  run_all_tests_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.18.0"
      - run: yarn global add lerna
      - run: yarn install
      - run: yarn test:ci
      - run: yarn build:packages
      - run: yarn cy:ci
      - uses: codecov/codecov-action@v2
      - run: cd ./applications/web-app && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOLITAIRE95_4B3B8 }}"
          channelId: live
          projectId: solitaire95-4b3b8
